{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "callstack.fullname" . }}-prometheus-pvc
  labels:
    {{- include "callstack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitoring.prometheus.persistence.size }}
{{- end }}
---
{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "callstack.fullname" . }}-grafana-pvc
  labels:
    {{- include "callstack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.monitoring.grafana.persistence.size }}
{{- end }}